(function(){
'use strict';
var API=window.ReisenProgress,progress=API.load(),wg=progress.lesson1.games.woher;
var countries=[
{name:'Deutschland',label:'Deutschland',prep:'aus',grammar:'aus',flag:'de'},{name:'Österreich',label:'Österreich',prep:'aus',grammar:'aus',flag:'at'},{name:'Schweiz',label:'die Schweiz',prep:'aus der',grammar:'ausDer',flag:'ch'},{name:'Frankreich',label:'Frankreich',prep:'aus',grammar:'aus',flag:'fr'},{name:'Spanien',label:'Spanien',prep:'aus',grammar:'aus',flag:'es'},{name:'Türkei',label:'die Türkei',prep:'aus der',grammar:'ausDer',flag:'tr'},{name:'Eritrea',label:'Eritrea',prep:'aus',grammar:'aus',flag:'er'},{name:'Südafrika',label:'Südafrika',prep:'aus',grammar:'aus',flag:'za'},{name:'USA',label:'die USA',prep:'aus den',grammar:'ausDen',flag:'us'}];
var people={Anna:'Anna',Max:'Max',Miriam:'Miriam',Ali:'Ali',Sofia:'Sofia',Daniel:'Daniel'};
function byName(n){return countries.find(function(c){return c.name===n})}
function sentence(s,c){return s+' '+(s==='Ich'?'komme':'kommt')+' '+c.prep+' '+c.name+'.'}
function q(type,name,subject,person){var c=byName(name),s=subject||'Ich';return {type:type,country:c,subject:s,person:person||'',sentence:sentence(s,c),attempts:0,hint:false,help:false}}
function shuffle(a){a=a.slice();for(var i=a.length-1;i;i--){var j=Math.floor(Math.random()*(i+1)),t=a[i];a[i]=a[j];a[j]=t}return a}
function questions(){var a=[q(3,'Österreich','Er','Max'),q(3,'Schweiz','Sie','Miriam'),q(3,'USA','Ich'),q(1,'Deutschland','Anna','Anna'),q(2,'Frankreich'),q(1,'Spanien','Ali','Ali'),q(2,'Türkei'),q(1,'Eritrea','Sofia','Sofia'),q(2,'Südafrika'),q(2,'Deutschland')];a=shuffle(a);a[2].special='gold';a[7].mystery=true;return a}
function svg(id){if(id==='plane')return '<svg viewBox="0 0 100 64" aria-hidden="true"><path d="M5 34 91 7 65 56 46 39 24 52 28 34z" fill="#fff1cb" stroke="#08758a" stroke-width="6"/><path d="m27 34 45-15-27 21" fill="none" stroke="#08758a" stroke-width="5"/></svg>';if(id==='cart')return '<svg viewBox="0 0 140 82" aria-hidden="true"><path d="M13 18h111l-10 43H24z" fill="#08758a" stroke="#073f50" stroke-width="6"/><path d="M20 17 12 5M120 17l9-12" stroke="#073f50" stroke-width="6"/><circle cx="39" cy="69" r="9" fill="#f4ae18" stroke="#073f50" stroke-width="5"/><circle cx="101" cy="69" r="9" fill="#f4ae18" stroke="#073f50" stroke-width="5"/></svg>';return '<svg viewBox="0 0 64 64" aria-hidden="true"><rect x="7" y="17" width="50" height="39" rx="7" fill="#a85b16" stroke="#073f50" stroke-width="4"/><path d="M23 17V9h18v8M18 18v38M46 18v38" fill="none" stroke="#f4ae18" stroke-width="4"/></svg>'}
function markup(){return '<div class="lc-app"><header class="lc-header"><a class="lc-logo" href="../index.html">'+svg('plane')+'<span>Reisen</span></a><div class="lc-global"><span>Level <b id="lcLevel">1</b></span><span>XP <b id="lcXP">0</b></span><span>Reisepunkte <b id="lcTravel">0</b></span><span>Bonus-Koffer <b id="lcCase">0 / 3</b></span></div><div class="lc-actions"><button class="lc-icon" id="lcSound" aria-label="Ton umschalten">♪</button><a class="lc-icon" href="../index.html" aria-label="Startseite">⌂</a></div></header><div class="lc-board"><b id="lcRound">RUNDE 1</b><span>LADE DAS FLUGZEUG</span><strong id="lcLoadedTop">0 / 10</strong></div><main class="lc-main"><aside class="lc-side"><span>REISESTATION 04</span><h1>LUGGAGE CATCH</h1><p>WOHER?</p><div class="lc-plane-window">'+svg('plane')+'</div><b>GELADEN</b><div class="lc-load" id="lcLoaded">0 / 10</div><p>Kein Zeitdruck</p></aside><section class="lc-game" id="lcGame"><div class="lc-target"><div><small>AKTIVES ZIEL</small><strong id="lcTarget">AUS</strong></div><b id="lcInstruction">Fang den richtigen Koffer.</b><span class="lc-mode" id="lcMode">FANGEN</span></div><div class="lc-field" id="lcField"><div class="lc-lanes" id="lcLanes"></div><div class="lc-cart" id="lcCart" data-lane="0">'+svg('cart')+'</div><button class="lc-catch" id="lcCatch">FANGEN</button><div class="lc-controls"><button class="lc-move" id="lcLeft" aria-label="Wagen nach links">←</button><button class="lc-move" id="lcRight" aria-label="Wagen nach rechts">→</button></div></div></section><aside class="lc-hud"><div class="lc-stats"><div class="lc-stat"><small>Fangpunkte</small><b id="lcScore">0</b></div><div class="lc-stat"><small>Bestwert</small><b id="lcBest">0</b></div><div class="lc-stat"><small>Sortier-Serie</small><b id="lcCombo">x0</b></div><div class="lc-stat"><small>Perfekte Fänge</small><b id="lcPerfect">0</b></div></div><h3>Herkunfts-Siegel</h3><div class="lc-seals" id="lcSeals"></div><button class="lc-secondary" id="lcHint">Detektiv-Hilfe</button><label class="lc-calm"><input type="checkbox" id="lcCalm"> Ruhiger Modus</label></aside></main><div id="lcLive" class="sr-only" aria-live="assertive"></div></div>'}
document.body.innerHTML=markup();
var run={list:[],index:0,final:false,finalList:[],score:0,combo:0,maxCombo:0,correct:0,perfect:0,gold:0,lane:0,selected:[],locked:false,helpReady:false};
function el(id){return document.getElementById(id)}
function saveExtra(){var x={completionRewardClaimed:!!wg.completionRewardClaimed,bestCombo:wg.bestCombo||0,plays:wg.plays||0,correctAnswers:wg.correctAnswers||0,totalAnswers:wg.totalAnswers||0,perfectCases:wg.perfectCases||0,grammarMastery:wg.grammarMastery||{aus:0,ausDer:0,ausDen:0},seals:wg.seals||[],borderControlCompleted:!!wg.borderControlCompleted,perfectBorderControl:!!wg.perfectBorderControl,introSeen:true,boardingTutorialSeen:!!wg.boardingTutorialSeen,baggageTutorialSeen:!!wg.baggageTutorialSeen,luggageCatchTutorialSeen:!!wg.luggageCatchTutorialSeen};try{localStorage.setItem('reisenWoherProgress',JSON.stringify(x));localStorage.setItem('woher-game-best-score',String(wg.bestScore||0))}catch(e){}API.save(progress)}
function update(){var level=API.getLevel(progress.player.totalXP),total=run.final?run.list.length+run.finalList.length:run.list.length,loaded=run.final?run.list.length+run.index:run.index;el('lcLevel').textContent=level.level;el('lcXP').textContent=progress.player.totalXP;el('lcTravel').textContent=progress.player.totalPoints;el('lcCase').textContent=progress.bonuses.suitcaseProgress+' / 3';el('lcLoaded').textContent=loaded+' / '+total;el('lcLoadedTop').textContent=loaded+' / '+total;el('lcScore').textContent=run.score;el('lcBest').textContent=Math.max(wg.bestScore||0,Number(localStorage.getItem('woher-game-best-score')||0));el('lcCombo').textContent=run.combo>=5?'EXPRESS!':'x'+run.combo;el('lcPerfect').textContent=run.perfect;el('lcGame').classList.toggle('express',run.combo>=5);var seals=wg.seals||[];el('lcSeals').innerHTML=[['aus','AUS'],['ausDer','AUS DER'],['ausDen','AUS DEN']].map(function(x){return '<span class="lc-seal '+(seals.indexOf(x[0])>=0?'on':'')+'">HERKUNFT<br>'+x[1]+'<br>'+(seals.indexOf(x[0])>=0?'✓':'?')+'</span>'}).join('');saveExtra()}
function current(){return run.final?run.finalList[run.index]:run.list[run.index]}
function flag(c){return '<img src="assets/woher/flags/'+c.flag+'.svg" alt="Flagge '+c.label+'">'}
function wrongSentences(x){var c=x.country,s=x.subject,v=s==='Ich'?'komme':'kommt';return shuffle([s+' '+v+' aus '+c.name+'.',s+' bin '+c.prep+' '+c.name+'.',s+' '+v+' aus den '+c.name+'.',s+' '+v+' aus der '+c.name+'.',s+' '+v+' in '+c.name+'.'].filter(function(y,i,a){return y!==x.sentence&&a.indexOf(y)===i})).slice(0,2)}
function render(){run.locked=false;run.lane=0;run.selected=[];el('lcCart').dataset.lane='0';var x=current();el('lcRound').textContent=run.final?'LETZTER AUFRUF · '+(run.index+1)+' / 3':'RUNDE '+(run.index+1)+' / '+run.list.length;el('lcHint').disabled=false;if(x.type===1)renderCatch(x);else if(x.type===2)renderScanner(x);else renderBuilder(x);update();announce('Neuer Koffer. Aufgabe bereit.')}
function candidatePool(x){var other=shuffle(countries.filter(function(c){return c.grammar!==x.country.grammar})).slice(0,2);return shuffle([x.country].concat(other))}
function bag(c,x){var cls='lc-bag'+(x.special==='gold'?' gold':'')+(x.mystery?' mystery':'');return '<div class="'+cls+'">'+flag(c)+'<b>'+c.label+'</b></div>'}
function lanes(items,html){el('lcLanes').innerHTML=items.map(function(item,i){return '<div class="lc-lane '+(i===0?'selected':'')+'" data-i="'+i+'">'+html(item)+'</div>'}).join('');document.querySelectorAll('.lc-lane').forEach(function(n){n.onclick=function(){move(Number(n.dataset.i))}})}
function renderCatch(x){el('lcTarget').textContent=x.country.prep.toUpperCase();el('lcInstruction').textContent='Fang nur passende Koffer.';el('lcMode').textContent='FANGEN';el('lcCatch').textContent='FANGEN';el('lcCatch').hidden=false;el('lcCart').hidden=false;el('lcLeft').hidden=el('lcRight').hidden=false;var items=candidatePool(x);x.wave=items;lanes(items,function(c){return bag(c,x)});el('lcCatch').onclick=function(){check(items[run.lane].grammar===x.country.grammar,x)}}
function renderScanner(x){el('lcTarget').textContent='RICHTIGER SATZ';el('lcInstruction').textContent='Fahre zum richtigen Etikett und scanne.';el('lcMode').textContent='SCANNER';el('lcCatch').textContent='SCANNEN';el('lcCatch').hidden=false;el('lcCart').hidden=false;el('lcLeft').hidden=el('lcRight').hidden=false;var items=shuffle([x.sentence].concat(wrongSentences(x)));x.wave=items;lanes(items,function(s){return '<div class="lc-scanner-tag">'+s+'</div>'});el('lcCatch').onclick=function(){check(items[run.lane]===x.sentence,x)}}
function renderBuilder(x){el('lcTarget').textContent='KOFFERTAG';el('lcInstruction').textContent='Fange die Wort-Tags in der richtigen Reihenfolge.';el('lcMode').textContent='TAG BAUEN';el('lcCatch').hidden=true;el('lcCart').hidden=true;el('lcLeft').hidden=el('lcRight').hidden=true;var words=x.sentence.replace('.',' .').split(' ').map(function(t,i){return {t:t,i:i}});el('lcLanes').innerHTML='<div class="lc-tag-stage"><div class="lc-tag-answer" id="lcAnswer"></div><div class="lc-tag-belt" id="lcWords"></div><div class="lc-tag-actions"><button class="lc-secondary" id="lcUndo">↶ Wort</button><button class="lc-secondary" id="lcReset">Zurücksetzen</button><button class="lc-primary" id="lcCheck">TAG PRÜFEN</button></div></div>';shuffle(words).forEach(function(w){var b=document.createElement('button');b.className='lc-word';b.textContent=w.t;b.onclick=function(){if(run.locked||b.disabled)return;b.disabled=true;run.selected.push({w:w,b:b});drawAnswer()};el('lcWords').appendChild(b)});el('lcUndo').onclick=undo;el('lcReset').onclick=function(){while(run.selected.length)undo()};el('lcCheck').onclick=function(){var built=run.selected.map(function(v){return v.w.t}).join(' ').replace(' .','.');check(built===x.sentence,x)};drawAnswer()}
function drawAnswer(){var a=el('lcAnswer');if(!a)return;a.innerHTML=run.selected.length?'':'<span>Wort-Tags hier sammeln …</span>';run.selected.forEach(function(v,i){var b=document.createElement('button');b.className='lc-word';b.textContent=v.w.t;b.onclick=function(){run.selected.splice(i,1);v.b.disabled=false;drawAnswer()};a.appendChild(b)})}
function undo(){var v=run.selected.pop();if(v){v.b.disabled=false;drawAnswer()}}
function move(i){run.lane=Math.max(0,Math.min(2,i));el('lcCart').dataset.lane=String(run.lane);document.querySelectorAll('.lc-lane').forEach(function(n,j){n.classList.toggle('selected',j===run.lane)});announce('Wagen auf Spur '+(run.lane+1))}
function check(ok,x){if(run.locked)return;x.attempts++;wg.totalAnswers=(wg.totalAnswers||0)+1;if(!ok){run.combo=0;run.score=Math.max(0,run.score-10);flash('Fast! Falscher Koffer.','bad');sound('wrong');update();return}run.locked=true;var perfect=x.attempts===1&&!x.hint&&!x.help;run.correct++;run.combo++;run.maxCombo=Math.max(run.maxCombo,run.combo);run.score+=100+(run.combo>=5?30:0)+(x.special?50:0);if(perfect){run.perfect++;run.score+=30}wg.correctAnswers=(wg.correctAnswers||0)+1;wg.perfectCases=(wg.perfectCases||0)+(perfect?1:0);wg.grammarMastery=wg.grammarMastery||{aus:0,ausDer:0,ausDen:0};wg.grammarMastery[x.country.grammar]=(wg.grammarMastery[x.country.grammar]||0)+1;API.addPoints(progress,25+(x.special?10:0));API.addXP(progress,20+(perfect?10:0));var bonus=API.updateSuitcase(progress,true);unlockSeal(x.country.grammar);if(x.special){run.gold++;flash('GOLDKOFFER! Sprache schlägt Gold.')}else flash(perfect?'Perfekt gefangen!':'Richtig! Koffer geladen.');sound('correct');if(bonus.ready)run.helpReady=true;update();setTimeout(advance,650)}
function unlockSeal(g){var need={aus:3,ausDer:2,ausDen:1};wg.seals=wg.seals||[];if(wg.grammarMastery[g]>=need[g]&&wg.seals.indexOf(g)<0){wg.seals.push(g);API.unlockAchievement(progress,'woher-seal-'+g);flash('Neues Herkunfts-Siegel!')}}
function advance(){if(run.final){if(run.index<run.finalList.length-1){run.index++;render()}else finish()}else if(run.index<run.list.length-1){run.index++;render()}else lastCall()}
function lastCall(){run.final=true;run.index=0;run.finalList=[run.list.find(function(x){return x.type===1}),run.list.find(function(x){return x.type===2}),run.list.find(function(x){return x.type===3})].map(function(x){return q(x.type,x.country.name,x.subject,x.person)});modal('<h1>LETZTER AUFRUF</h1><h2>3 KOFFER FEHLEN</h2><p>Fangen, scannen und einen letzten Tag bauen.</p><button class="lc-primary" id="lcGo">LAST CALL STARTEN</button>',render)}
function finish(){wg.borderControlCompleted=true;wg.bestScore=Math.max(wg.bestScore||0,run.score);wg.bestCombo=Math.max(wg.bestCombo||0,run.maxCombo);var first=!wg.completed;API.completeGame(progress,'woher',run.score);if(first){API.addPoints(progress,250);API.addXP(progress,100)}var all=['countryMap','dialoge','saetze','woher'].every(function(k){return progress.lesson1.games[k].completed});if(all&&!(progress.meta&&progress.meta.goldenPassportCelebrated)){progress.meta=progress.meta||{};progress.meta.goldenPassportCelebrated=true;progress.meta.goldenPassportUnlocked=true;API.save(progress);window.ReisenAudio&&ReisenAudio.playFinale();modal('<img src="assets/shared/goldener-reisepass.svg" alt="Goldener Reisepass" style="max-width:260px"><h1>Lektion 1 geschafft!</h1><p>DEUTSCHREISE GESCHAFFT · 4 / 4</p><button class="lc-primary" id="lcReplay">Noch eine Runde</button> <a class="lc-secondary" href="../index.html">Zur Deutschreise</a>',null,true)}else results()}
function results(){var left=Math.max(0,3-(wg.seals||[]).length);modal('<h1>ALLES VERLADEN!</h1><div class="lc-modal-grid"><div>Fangpunkte<br><b>'+run.score+'</b></div><div>Richtige Koffer<br><b>'+run.correct+'</b></div><div>Beste Sortier-Serie<br><b>x'+run.maxCombo+'</b></div><div>Perfekte Fänge<br><b>'+run.perfect+'</b></div><div>Goldkoffer<br><b>'+run.gold+'</b></div><div>Herkunfts-Siegel<br><b>'+(wg.seals||[]).length+' / 3</b></div><div>Bestwert<br><b>'+wg.bestScore+'</b></div><div>Deutschreise<br><b>'+API.getLessonProgress(progress).count+' / 4</b></div></div><p>'+(left?'Noch '+left+' Herkunfts-Siegel.':'Alle Herkunfts-Siegel gesammelt!')+'</p><button class="lc-primary" id="lcReplay">Noch eine Runde</button> <a class="lc-secondary" href="../index.html">Zur Deutschreise</a>',null,true)}
function flash(t,bad){var old=document.querySelector('.lc-feedback');if(old)old.remove();var d=document.createElement('div');d.className='lc-feedback'+(bad?' bad':'');d.textContent=t;el('lcField').appendChild(d);announce(t);setTimeout(function(){d.remove()},700)}
function announce(t){el('lcLive').textContent=t}
function modal(html,after,replay){var o=document.createElement('div');o.className='lc-overlay';o.innerHTML='<div class="lc-modal" role="dialog" aria-modal="true">'+html+'</div>';document.body.appendChild(o);var go=o.querySelector('#lcGo');if(go)go.onclick=function(){o.remove();after&&after()};var r=o.querySelector('#lcReplay');if(r)r.onclick=function(){o.remove();start()}}
function intro(){modal('<div style="width:100px;margin:auto">'+svg('cart')+'</div><span>REISESTATION 04</span><h1>LUGGAGE CATCH</h1><h2>WOHER? · FANG DIE RICHTIGEN KOFFER</h2><p>Fang die richtigen Koffer und lade das Flugzeug.</p><div class="lc-actions-row"><button class="lc-primary" id="lcGo">Spiel starten</button><button class="lc-secondary" id="lcHow">Wie spielt man?</button></div>',function(){if(wg.luggageCatchTutorialSeen)start();else tutorial()});setTimeout(function(){var h=document.getElementById('lcHow');if(h)h.onclick=function(){h.closest('.lc-overlay').remove();tutorial()}},0)}
function tutorial(){modal('<h1>So spielst du</h1><div class="lc-modal-grid"><div><b>1 · Schau auf das Ziel.</b><br>AUS, AUS DER oder AUS DEN.</div><div><b>2 · Lies den Koffer.</b><br>Land und Flagge helfen dir.</div><div><b>3 · Fang nur richtige Koffer.</b><br>Bewege den Wagen zur Spur.</div><div><b>4 · Lade das Flugzeug.</b><br>Scanner und Tag-Runden wechseln sich ab.</div></div><button class="lc-primary" id="lcGo">Spiel starten</button>',function(){wg.luggageCatchTutorialSeen=true;saveExtra();start()})}
function start(){window.ReisenAudio&&ReisenAudio.playMusic();run.list=questions();run.index=run.score=run.combo=run.maxCombo=run.correct=run.perfect=run.gold=0;run.final=false;run.finalList=[];wg.plays=(wg.plays||0)+1;render()}
function sound(t){try{var A=window.AudioContext||window.webkitAudioContext,c=sound.ctx||(sound.ctx=new A()),o=c.createOscillator(),g=c.createGain();o.frequency.value=t==='wrong'?180:620;g.gain.value=.04;o.connect(g).connect(c.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.15);o.stop(c.currentTime+.16)}catch(e){}}
function setupAudio(){var soundButton=el('lcSound'),musicButton=document.createElement('button'),speakButton=document.createElement('button');musicButton.className='lc-icon';musicButton.type='button';musicButton.textContent='♫';musicButton.setAttribute('aria-label','Musik umschalten');soundButton.parentNode.insertBefore(musicButton,soundButton);soundButton.textContent='◖))';soundButton.onclick=function(){var on=!ReisenAudio.isSoundEnabled();ReisenAudio.setSoundEnabled(on);soundButton.classList.toggle('off',!on)};musicButton.onclick=function(){var settings=ReisenAudio.getSettings(),on=!settings.musicEnabled;ReisenAudio.setMusicEnabled(on);musicButton.classList.toggle('off',!on)};speakButton.className='lc-icon';speakButton.type='button';speakButton.textContent='Hören';speakButton.setAttribute('aria-label','Deutschen Satz vorlesen');el('lcMode').parentNode.insertBefore(speakButton,el('lcMode'));speakButton.onclick=function(){var x=current();if(x)ReisenAudio.speak(x.sentence,{rate:.88})}}
setupAudio();
el('lcLeft').onclick=function(){move(run.lane-1)};el('lcRight').onclick=function(){move(run.lane+1)};el('lcCalm').checked=matchMedia('(prefers-reduced-motion: reduce)').matches;el('lcCalm').onchange=function(){document.body.classList.toggle('lc-calm',this.checked)};document.body.classList.toggle('lc-calm',el('lcCalm').checked);el('lcHint').onclick=function(){var x=current();x.hint=true;x.help=true;flash(x.country.grammar==='ausDer'?'Achte auf den femininen Artikel.':x.country.grammar==='ausDen'?'Achte auf den Plural.':'Dieses Land steht ohne Artikel.')};document.addEventListener('keydown',function(e){if(document.querySelector('.lc-overlay'))return;if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a'){e.preventDefault();move(run.lane-1)}else if(e.key==='ArrowRight'||e.key.toLowerCase()==='d'){e.preventDefault();move(run.lane+1)}else if((e.key==='Enter'||e.key===' ')&&!el('lcCatch').hidden){e.preventDefault();el('lcCatch').click()}});document.addEventListener('visibilitychange',function(){document.body.classList.toggle('lc-calm',document.hidden||el('lcCalm').checked)});update();intro();
})();
