(function(){
'use strict';
var oldBest=Number(localStorage.getItem('woher-game-best-score')||0);
var API=window.ReisenProgress;
var CONFIG={correctPoints:100,correctXP:20,correctTravel:25,perfectPoints:30,perfectXP:10,perfectTravel:10,mysteryPoints:50,mysteryXP:10,sealXP:25,completionXP:100,completionTravel:250,borderXP:40,perfectBorderXP:50,suitcaseEvery:3,bonusChoiceThreshold:3,maxBonusChoicesPerRun:1,safeChoicePoints:75,riskChoicePoints:150};
var countries=[
{name:'Deutschland',label:'Deutschland',prep:'aus',grammar:'aus',flag:'flag-de',explain:'Deutschland → aus Deutschland'},
{name:'Österreich',label:'Österreich',prep:'aus',grammar:'aus',flag:'flag-at',explain:'Österreich → aus Österreich'},
{name:'Schweiz',label:'die Schweiz',prep:'aus der',grammar:'ausDer',flag:'flag-ch',explain:'die Schweiz → aus der Schweiz'},
{name:'Frankreich',label:'Frankreich',prep:'aus',grammar:'aus',flag:'flag-fr',explain:'Frankreich → aus Frankreich'},
{name:'Spanien',label:'Spanien',prep:'aus',grammar:'aus',flag:'flag-es',explain:'Spanien → aus Spanien'},
{name:'Türkei',label:'die Türkei',prep:'aus der',grammar:'ausDer',flag:'flag-tr',explain:'die Türkei → aus der Türkei'},
{name:'Eritrea',label:'Eritrea',prep:'aus',grammar:'aus',flag:'flag-er',explain:'Eritrea → aus Eritrea'},
{name:'Südafrika',label:'Südafrika',prep:'aus',grammar:'aus',flag:'flag-za',explain:'Südafrika → aus Südafrika'},
{name:'USA',label:'die USA',prep:'aus den',grammar:'ausDen',flag:'flag-us',explain:'die USA → aus den USA'}];
var people=[{name:'Anna',portrait:'person-anna',pronoun:'Sie'},{name:'Max',portrait:'person-max',pronoun:'Er'},{name:'Miriam',portrait:'person-miriam',pronoun:'Sie'},{name:'Ali',portrait:'person-ali',pronoun:'Er'},{name:'Sofia',portrait:'person-sofia',pronoun:'Sie'},{name:'Daniel',portrait:'person-daniel',pronoun:'Er'}];
function asset(id,cls,label){var art={plane:'<path d="M5 31 57 7 40 56l-9-18-13 11 1-15z" fill="#fff4d7" stroke="#08758a" stroke-width="5" stroke-linejoin="round"/><path d="m19 34 26-17-14 21" fill="none" stroke="#08758a" stroke-width="4"/>',star:'<path d="m32 4 8 18 20 2-15 14 4 20-17-10-18 10 5-20L4 24l20-2z" fill="#f4ae18" stroke="#9a5900" stroke-width="3"/>',suitcase:'<rect x="7" y="17" width="50" height="39" rx="7" fill="#a85b16" stroke="#073f50" stroke-width="4"/><path d="M23 17V9h18v8M18 18v38M46 18v38" fill="none" stroke="#f4ae18" stroke-width="4"/><circle cx="22" cy="35" r="5" fill="#08758a"/>',home:'<path d="m7 30 25-22 25 22-7 1v25H14V31z" fill="#073f50"/><path d="M27 56V39h11v17" fill="#fff4d7"/>',sound:'<path d="M8 25h12L36 12v40L20 39H8z" fill="#073f50"/><path d="M44 22c7 6 7 14 0 20M50 15c13 11 13 23 0 34" fill="none" stroke="#08758a" stroke-width="5" stroke-linecap="round"/>',mute:'<path d="M8 25h12L36 12v40L20 39H8z" fill="#073f50"/><path d="m44 23 14 18M58 23 44 41" stroke="#f04418" stroke-width="5"/>',tip:'<path d="M20 38c-6-5-9-11-8-18C14 7 25 2 35 5c13 3 18 19 9 29l-6 6H24z" fill="#f4ae18" stroke="#8d5b00" stroke-width="3"/><path d="M24 47h14M26 54h10M31 15v12" stroke="#073f50" stroke-width="4"/>',search:'<circle cx="27" cy="27" r="18" fill="#dff3eb" stroke="#08758a" stroke-width="6"/><path d="m40 40 16 16" stroke="#073f50" stroke-width="8" stroke-linecap="round"/>',passport:'<rect x="12" y="5" width="40" height="54" rx="5" fill="#073f50" stroke="#d59b1d" stroke-width="3"/><circle cx="32" cy="30" r="12" fill="none" stroke="#f4ae18" stroke-width="3"/><path d="M20 48h24M32 18v24M20 30h24" stroke="#f4ae18" stroke-width="2"/>',checkpoint:'<path d="M12 58V16h40v42M8 16h48L50 6H14z" fill="#fff4d7" stroke="#073f50" stroke-width="4"/><path d="M22 58V28h20v30" fill="#dff3eb" stroke="#08758a" stroke-width="4"/>',seal:'<circle cx="32" cy="32" r="25" fill="#fff4d7" stroke="#08758a" stroke-width="4" stroke-dasharray="6 3"/><path d="m20 32 8 8 17-19" fill="none" stroke="#167c35" stroke-width="6"/>'};return '<svg viewBox="0 0 64 64" class="asset '+(cls||'')+'"'+(label?' role="img" aria-label="'+label+'"':' aria-hidden="true"')+'>'+art[id]+'</svg>'}
function extraDefaults(){return {completionRewardClaimed:false,bestCombo:0,plays:0,correctAnswers:0,totalAnswers:0,perfectCases:0,specialBaggage:0,grammarMastery:{aus:0,ausDer:0,ausDen:0},seals:[],borderControlCompleted:false,perfectBorderControl:false,introSeen:false,boardingTutorialSeen:false,baggageTutorialSeen:false}}
function merge(base,src){if(!src||typeof src!=='object')return base;Object.keys(src).forEach(function(k){if(src[k]&&typeof src[k]==='object'&&!Array.isArray(src[k])&&base[k]&&typeof base[k]==='object')merge(base[k],src[k]);else if(src[k]!==undefined)base[k]=src[k]});return base}
var progress=API.load(),wg=progress.lesson1.games.woher,extra=(function(){try{return merge(extraDefaults(),JSON.parse(localStorage.getItem('reisenWoherProgress')||'{}'))}catch(e){return extraDefaults()}})();
Object.keys(extra).forEach(function(k){wg[k]=extra[k]});wg.bestScore=Math.max(wg.bestScore||0,oldBest);
function save(){Object.keys(extraDefaults()).forEach(function(k){extra[k]=wg[k]});API.save(progress);try{localStorage.setItem('reisenWoherProgress',JSON.stringify(extra));localStorage.setItem('woher-game-best-score',String(wg.bestScore||0))}catch(e){}}
function completedCount(){var g=progress.lesson1.games;return ['countryMap','dialoge','saetze','woher'].filter(function(k){return !!g[k].completed}).length}
function addXP(n){var result=API.addXP(progress,n);if(result.leveledUp)toast('Level aufgestiegen! · Level '+result.after.level)}
function awardAchievement(id,label){if(API.unlockAchievement(progress,id))toast('Erfolg freigeschaltet: '+label)}
function byName(n){return countries.find(function(c){return c.name===n})}
function sentence(subject,c){return subject+' '+(subject==='Ich'?'komme':'kommt')+' '+c.prep+' '+c.name+'.'}
function shuffle(a){a=a.slice();for(var i=a.length-1;i;i--){var j=Math.floor(Math.random()*(i+1)),x=a[i];a[i]=a[j];a[j]=x}return a}
function makeQ(type,name,subject,person){var c=byName(name);return {type:type,country:c,subject:subject||'Ich',person:person||null,sentence:sentence(subject||'Ich',c),grammar:c.grammar,attempts:0,hint:false,help:false,solved:false,mystery:false}}
function makeQuestions(){var list=[
makeQ(3,'Österreich','Er',people[1]),makeQ(3,'Schweiz','Sie',people[2]),makeQ(3,'USA','Ich'),
makeQ(1,'Deutschland',people[0].name,people[0]),makeQ(2,'Frankreich'),makeQ(1,'Spanien',people[3].name,people[3]),
makeQ(2,'Türkei'),makeQ(1,'Eritrea',people[4].name,people[4]),makeQ(2,'Südafrika'),makeQ(2,'Deutschland')];
list=shuffle(list);list[Math.floor(Math.random()*list.length)].mystery=true;return list}
var run={questions:[],index:0,score:0,combo:0,maxCombo:0,correct:0,errors:0,perfect:0,special:0,phase:'normal',border:[],borderIndex:0,borderPerfect:true,selected:[],locked:false,sound:localStorage.getItem('woher-game-sound-enabled')!=='false',bonusChoices:0,riskBonus:false,suitcaseReady:false,helpReady:false,stamped:false};
function appMarkup(){return '<div class="reisen-shell">'+
'<header class="global-header"><div class="head-cell logo-cell"><a class="logo" href="../index.html" aria-label="Reisen Startseite">'+asset('plane','logo-plane')+'<span>Reisen<small>Deine Deutschreise</small></span></a></div>'+
'<div class="head-cell level"><div class="level-shield">Lv.<br><b id="level">1</b></div><div class="head-value"><span id="levelName">Reisender</span><small id="xpText">XP</small><div class="xpbar"><i id="xpFill"></i></div></div></div>'+
'<div class="head-cell points">'+asset('star','header-asset')+'<div class="head-value"><span id="travelPoints">0</span><small>Reisepunkte</small></div></div>'+
'<div class="head-cell case-head">'+asset('suitcase','header-asset')+'<div class="head-value">Koffer <span id="caseCount">0 / 3</span><div class="tinybar"><i id="caseFill"></i></div></div></div>'+
'<div class="head-cell">'+asset('passport','header-pass')+'<b>Reisepass</b></div><div class="head-cell head-actions"><button id="sound" class="icon-btn" aria-label="Ton umschalten">'+asset('sound','button-asset')+'</button><a class="icon-btn" href="../index.html" aria-label="Startseite">'+asset('home','button-asset')+'<small>Home</small></a></div></header>'+
 '<div class="case-route departure-board"><div><small>REISEN GEPÄCK · FLUG 04</small><div class="route-title" id="routeTitle">VERLADEN · 0 / 10</div></div><div class="route-dots" id="routeDots"></div><b id="boardStatus">BAND BEREIT</b></div>'+
'<main class="station-layout control-simulator baggage-world"><aside class="paper-card passenger-panel loading-panel"><span class="station-ribbon">KOFFER-CHAOS</span><div class="airport-sign">WOHER?<small>Das Gepäck-Sortierspiel</small></div><div class="airport-window" aria-hidden="true"><span class="cloud one"></span><span class="cloud two"></span><div id="airportPlane" class="airport-plane">'+asset('plane','')+'</div></div><h3>IM FLUGZEUG</h3><strong id="loadedCount">0 / 10</strong><div class="loaded-stack" id="loadedStack" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></div><div class="gate cargo-door" id="controlGate"><i></i><b>LADEZONE</b></div><div class="queue" aria-label="Weitere Koffer warten"><i></i><i></i><i></i><span>Kein Zeitdruck</span></div></aside>'+
'<section class="paper-card center-card passport-desk sorting-hall" id="center"><div class="desk-top"><span>GEPÄCK-SORTIERUNG</span><div id="controlLight" class="control-light waiting"><i></i><b>STOPPZONE</b></div><span id="checkedCount">0 Koffer verladen</span></div><div class="conveyor-field" aria-hidden="true"><div class="scanner-arch"><b>SCANNER</b><i></i></div><div class="belt"><i></i><i></i><i></i><i></i><i></i></div><div id="passengerStage" class="passenger-stage luggage-stage arriving"><div id="passengerPortrait" class="current-suitcase">'+asset('suitcase','')+'<span id="passengerName">KOFFER</span></div><span id="passengerState">wartet in der Stoppzone</span></div><div class="sort-junction" id="sortJunction"><i></i></div><div class="route-chutes"><b>AUS</b><b>AUS DER</b><b>AUS DEN</b></div></div><div id="caseDocument" class="case-document baggage-console" aria-live="polite"><div class="boarding-pass-head"><b id="modeTitle">GEPÄCK-AUFGABE</b><span id="passStatus">PRÜFEN</span></div><div class="case-inner" id="caseArea"></div><div id="documentStamp" class="document-stamp" hidden>ETIKETT ✓</div></div><div id="stampZone" class="stamp-zone" hidden><button class="stamp-button" id="stampButton" type="button">'+asset('suitcase','inline-asset')+'<b>BAND STARTEN</b></button><span>Starte das Band und bringe den Koffer zum Flugzeug.</span></div></section>'+
 '<aside class="right-panel"><div class="paper-card stats-card"><div class="mini-stat"><small>Sortierpunkte</small><strong id="score">0</strong></div><div class="mini-stat"><small>Bestwert</small><strong id="best">0</strong></div><div class="mini-stat"><small>Sortier-Serie</small><strong id="combo">x0</strong></div></div>'+
'<div class="paper-card suitcase-card"><h3>Bonus-Koffer</h3><div class="suitcase-row">'+asset('suitcase','suitcase-icon')+'<div><b id="suitcaseText">0 / 3</b><div class="tinybar"><i id="suitcaseFill"></i></div><small>Der nächste Fall füllt den Koffer.</small></div></div></div>'+
'<div class="passport-card"><div class="passport-page"><h2>MEIN REISEPASS</h2><div class="tabs"><span>Länder</span><span>Dialoge</span><span>Sätze</span><span class="active">Woher?</span></div><h3>Meine Herkunfts-Siegel</h3><div class="seals" id="seals"></div><div class="mastery" id="mastery"></div></div></div></aside></main>'+
'<nav class="bottom-route" aria-label="Deutschreise Fortschritt"><span class="station-node"><b>01</b>Länder</span><i class="connector"></i><span class="station-node"><b>02</b>Dialoge</span><i class="connector"></i><span class="station-node"><b>03</b>Sätze</span><i class="connector"></i><span class="station-node active"><b>04</b>Woher?</span><i class="connector"></i><span class="station-node"><b>'+asset('star','node-asset')+'</b>Ziel</span></nav><div id="live" class="sr-only" aria-live="assertive"></div></div>'}
document.body.innerHTML=appMarkup();
function el(id){return document.getElementById(id)}
function updateGlobal(){var level=API.getLevel(progress.player.totalXP),s={progress:progress.bonuses.suitcaseProgress,total:3};el('level').textContent=level.level;el('levelName').textContent=level.name;el('xpText').textContent=level.next?'XP '+progress.player.totalXP+' / '+level.next.xp:'XP '+progress.player.totalXP;el('xpFill').style.width=level.progress+'%';el('travelPoints').textContent=Number(progress.player.totalPoints||0).toLocaleString('de-DE');el('caseCount').textContent=s.progress+' / '+s.total;el('caseFill').style.width=s.progress/s.total*100+'%';el('suitcaseText').textContent=s.progress+' / '+s.total;el('suitcaseFill').style.width=s.progress/s.total*100+'%';el('best').textContent=Math.max(oldBest,wg.bestScore||0);el('score').textContent=run.score;el('combo').textContent=run.combo>=5?'EXPRESS-BAND!':run.combo>=3?'Gute Serie!':'x'+run.combo;el('combo').closest('.stats-card').classList.toggle('flow-hot',run.combo>=3);el('center').classList.toggle('express',run.combo>=5);renderPassport();save()}
function renderPassport(){var forms=[['aus','AUS'],['ausDer','AUS DER'],['ausDen','AUS DEN']];el('seals').innerHTML=forms.map(function(f){return '<div class="seal '+(wg.seals.indexOf(f[0])>=0?'unlocked':'')+'">HERKUNFT<br>'+f[1]+'<br>'+(wg.seals.indexOf(f[0])>=0?'✓ GEPRÜFT':'?')+'</div>'}).join('');var targets={aus:3,ausDer:2,ausDen:1};el('mastery').innerHTML=forms.map(function(f){var n=wg.grammarMastery[f[0]]||0,p=Math.min(100,n/targets[f[0]]*100);return '<div class="mastery-row"><span>'+f[1].toLowerCase()+'</span><div class="mastery-track"><i style="width:'+p+'%"></i></div><b>'+n+'</b></div>'}).join('')}
function route(){var total=run.phase==='border'?3:run.questions.length,current=run.phase==='border'?run.borderIndex:run.index;el('routeTitle').textContent=run.phase==='border'?'GEPÄCK-RUSH · NOCH '+(3-current)+' KOFFER':'VERLADEN · '+current+' / '+total+' KOFFER';el('boardStatus').textContent=run.phase==='border'?'LETZTER FLUG':current>=Math.ceil(total*.7)?'LADEZONE AKTIV':'BAND BEREIT';var out='';for(var i=0;i<total;i++){if(i)out+='<span></span>';out+='<i class="'+(i<current?'done':i===current?'current':'')+'">'+(i===current?asset('suitcase','route-plane'):'')+'</i>'}el('routeDots').innerHTML=out}
function currentQ(){return run.phase==='border'?run.border[run.borderIndex]:run.questions[run.index]}
function typeInfo(q){return q.type===1?['KOFFER SORTIEREN','Wähle das richtige Band.']:q.type===2?['GEPÄCK-SCANNER','Welches Gepäck-Etikett ist richtig?']:['KOFFER-TAG BAUEN','Baue den richtigen Koffer-Tag.']}
function flag(c){return '<img class="flag-image" src="assets/woher/flags/'+c.flag.replace('flag-','')+'.svg" alt="Flagge '+c.label+'">'}
function render(){run.locked=false;run.stamped=false;run.selected=[];route();updateGlobal();var q=currentQ(),info=typeInfo(q),a=el('caseArea'),center=el('center');center.classList.toggle('checkpoint',run.phase==='border');center.classList.remove('stamped','task-type-a','task-type-b','task-type-c','mode-sort','mode-scan','mode-tag','wrong-route');center.classList.add('task-type-'+(['a','b','c'][q.type-1]),['mode-sort','mode-scan','mode-tag'][q.type-1]);el('stampZone').hidden=true;el('documentStamp').hidden=true;el('documentStamp').className='document-stamp';el('documentStamp').textContent='ETIKETT ✓';el('passStatus').textContent='PRÜFEN';el('modeTitle').textContent=info[0];el('controlLight').className='control-light waiting';el('controlLight').querySelector('b').textContent='STOPPZONE';el('controlGate').classList.remove('open');el('sortJunction').className='sort-junction';el('passengerStage').className='passenger-stage luggage-stage arriving'+(q.mystery?' special':'');var loaded=run.phase==='border'?run.questions.length+run.borderIndex:run.index,total=run.phase==='border'?run.questions.length+3:run.questions.length;el('checkedCount').textContent=loaded+' Koffer verladen';el('loadedCount').textContent=loaded+' / '+total;Array.prototype.forEach.call(el('loadedStack').children,function(n,i){n.style.visibility=i<Math.min(5,Math.ceil(loaded/2))?'visible':'hidden'});var owner=q.person?q.person.name:'REISEN';el('passengerName').textContent=owner;el('passengerState').textContent='wartet in der Stoppzone';el('passengerPortrait').innerHTML=asset('suitcase','')+'<span id="passengerName">'+owner+'</span><small>'+flag(q.country)+'</small>';var top='<span class="task-badge">'+(run.phase==='border'?'GEPÄCK-RUSH · ':'')+info[0]+'</span>'+(q.mystery&&!q.solved?'<span class="mystery-chip">SONDERGEPÄCK</span>':'')+'<div class="prompt-wrap"><h2>'+info[1]+'</h2><p>'+(run.phase==='border'?'Noch '+(3-run.borderIndex)+' Koffer bis zum Start.':'Der Koffer wartet – du hast Zeit zum Lesen.')+'</p></div>';
var portrait=q.person?'<div class="person-badge"><img class="portrait-image" src="assets/woher/people/'+q.person.name.toLowerCase()+'.png?v=2" alt="Illustriertes Porträt von '+q.person.name+'"></div>':'<div class="case-emblem">'+asset('suitcase','')+'</div>';var context='<div class="context-row">'+portrait+'<div class="country-card">'+flag(q.country)+'<span>'+q.country.label+'</span></div></div>';
if(q.type===1){a.innerHTML=top+context+'<div class="sentence">'+q.subject+' kommt <span class="blank">___</span> '+q.country.name+'.</div>'+choices(shuffle(['aus','aus der','aus den','in der']),q.country.prep,q)}
else if(q.type===2){a.innerHTML=top+context+choices(shuffle([q.sentence].concat(wrongSentences(q))),q.sentence,q)}
else{a.innerHTML=top+context+'<div id="builderAnswer" class="builder-answer"><span style="color:#8a806d">Wörter hier auswählen …</span></div><div id="wordBank" class="word-bank"></div><p class="auto-check-note">Die Antwort wird automatisch geprüft, sobald alle Wörter eingesetzt sind.</p><div class="builder-actions"><button class="btn secondary" id="undo">↩ Wort</button><button class="btn secondary" id="reset">Zurücksetzen</button></div>';var words=q.sentence.replace('.',' .').split(' ');shuffle(words.map(function(w,i){return {text:w,id:i}})).forEach(function(o){var b=document.createElement('button');b.className='word';b.textContent=o.text;b.onclick=function(){if(b.disabled||run.locked)return;b.disabled=true;b.classList.add('selected');run.selected.push({button:b,obj:o});renderSelected();if(run.selected.length===words.length){var built=run.selected.map(function(x){return x.obj.text}).join(' ').replace(' .','.');answer(built===q.sentence,q)}};el('wordBank').appendChild(b)});el('undo').onclick=undo;el('reset').onclick=reset}
var tools=document.createElement('div');tools.className='builder-actions';tools.style.marginTop='18px';tools.innerHTML='<button class="btn secondary" id="tip">'+asset('tip','inline-asset')+'Tipp</button><button class="btn secondary" id="help">'+asset('search','inline-asset')+(run.helpReady?'Bonus-Hilfe':'Detektiv-Hilfe')+'</button><button class="btn secondary" id="hear">'+asset('sound','inline-asset')+'Hören</button>';a.appendChild(tools);el('tip').onclick=function(){q.hint=true;showHint('Sage den Satz langsam. Welcher Teil steht direkt vor dem Land?')};el('help').onclick=function(){q.help=true;if(run.helpReady){run.helpReady=false;toast('Bonus-Koffer: Detektiv-Hilfe eingesetzt')}showHint(q.grammar==='ausDer'?'Achte auf den femininen Artikel beim Land.':q.grammar==='ausDen'?'Achte auf den Artikel im Plural.':'Dieses Land steht hier ohne Artikel.')};el('hear').onclick=function(){speak(q.sentence)};var remaining=(run.phase==='border'?3-run.borderIndex:run.questions.length-run.index)-1;document.querySelectorAll('.queue i').forEach(function(n,i){n.style.visibility=i<Math.min(3,remaining)?'visible':'hidden'});document.body.classList.toggle('airport-mid',run.phase==='normal'&&run.index>=Math.ceil(run.questions.length/2));document.body.classList.toggle('airport-near',run.phase==='border'||(run.phase==='normal'&&run.index>=Math.ceil(run.questions.length*.8)));setTimeout(function(){el('passengerStage').classList.remove('arriving')},450);el('live').textContent='Neuer Koffer. Aufgabe bereit. '+info[0]+'. '+info[1]}
function choices(options,correct,q){return '<div class="choices">'+options.map(function(x,i){return '<button class="choice" data-value="'+x.replace(/"/g,'&quot;')+'"><span class="num">'+(i+1)+'</span>'+x+'</button>'}).join('')+'</div>'}
function bindChoices(){document.querySelectorAll('.choice').forEach(function(b){b.onclick=function(){var q=currentQ();answer(b.dataset.value===(q.type===1?q.country.prep:q.sentence),q,b)}})}
var observer=new MutationObserver(function(){bindChoices()});observer.observe(el('caseArea'),{childList:true,subtree:true});
function wrongSentences(q){var c=q.country,s=q.subject,v=s==='Ich'?'komme':'kommt';return shuffle([s+' '+v+' aus '+c.name+'.',s+' bin '+c.prep+' '+c.name+'.',s+' '+v+' aus den '+c.name+'.',s+' '+v+' aus der '+c.name+'.',s+' '+v+' in '+c.name+'.'].filter(function(x,i,a){return x!==q.sentence&&a.indexOf(x)===i})).slice(0,3)}
function renderSelected(){var box=el('builderAnswer');box.innerHTML=run.selected.length?'':'<span style="color:#8a806d">Wörter hier auswählen …</span>';run.selected.forEach(function(x,i){var s=document.createElement('button');s.type='button';s.className='word placed-word';s.textContent=x.obj.text;s.setAttribute('aria-label',x.obj.text+' entfernen');s.onclick=function(){run.selected.splice(i,1);x.button.disabled=false;x.button.classList.remove('selected');renderSelected()};s.onkeydown=function(e){if((e.key==='ArrowLeft'||e.key==='ArrowRight')&&run.selected.length>1){e.preventDefault();var j=e.key==='ArrowLeft'?i-1:i+1;if(j>=0&&j<run.selected.length){var hold=run.selected[i];run.selected[i]=run.selected[j];run.selected[j]=hold;renderSelected();box.children[j].focus()}}};box.appendChild(s)})}
function undo(){var x=run.selected.pop();if(x){x.button.disabled=false;x.button.classList.remove('selected');renderSelected()}}
function reset(){while(run.selected.length)undo()}
function showHint(t){var old=document.querySelector('.hint');if(old)old.remove();var d=document.createElement('div');d.className='hint';d.textContent=t;el('caseArea').appendChild(d);el('live').textContent=t}
function answer(ok,q,button){if(run.locked)return;q.attempts++;wg.totalAnswers++;document.querySelectorAll('.feedback').forEach(function(n){n.remove()});if(!ok){run.errors++;run.combo=0;if(run.phase==='border')run.borderPerfect=false;if(run.riskBonus){run.riskBonus=false;toast('Express-Bonus vorbei · Du kannst sicher weitersortieren')}if(button)button.classList.add('wrong');el('center').classList.add('wrong-route');el('controlLight').className='control-light bad';el('controlLight').querySelector('b').textContent='FAST!';el('passStatus').textContent='KORREKTUR';el('sortJunction').classList.add('reverse');el('passengerStage').classList.add('thinking','returning');showFeedback(false,q);updateGlobal();sound('wrong');return}run.locked=true;q.solved=true;run.correct++;run.combo++;run.maxCombo=Math.max(run.maxCombo,run.combo);var perfect=q.attempts===1&&!q.hint&&!q.help;run.score+=CONFIG.correctPoints;API.addPoints(progress,CONFIG.correctTravel);addXP(CONFIG.correctXP);wg.correctAnswers++;wg.grammarMastery[q.grammar]=(wg.grammarMastery[q.grammar]||0)+1;if(perfect){run.perfect++;wg.perfectCases++;run.score+=CONFIG.perfectPoints;API.addPoints(progress,CONFIG.perfectTravel);addXP(CONFIG.perfectXP);awardAchievement('woher-perfect','Perfekt sortiert')}if(run.riskBonus){if(perfect){run.score+=CONFIG.riskChoicePoints;toast('Express-Band geschafft! +'+CONFIG.riskChoicePoints+' Sortierpunkte')}else toast('Express-Bonus braucht eine perfekte Sortierung');run.riskBonus=false}if(run.combo>=5){run.score+=25;toast('EXPRESS-BAND! +25 Sortierpunkte')}if(q.mystery){run.score+=CONFIG.mysteryPoints;wg.specialBaggage++;addXP(CONFIG.mysteryXP);toast('Sondergepäck richtig verarbeitet!')}if(run.combo>=3)awardAchievement('woher-combo','Sortier-Serie');awardAchievement('woher-first','Erster Koffer sortiert');var suitcase=API.updateSuitcase(progress,true);if(suitcase.ready)run.suitcaseReady=true;checkSeal(q.grammar);if(button){button.classList.add('correct');document.querySelectorAll('.choice').forEach(function(b){b.disabled=true})}el('controlLight').className='control-light correct';el('controlLight').querySelector('b').textContent=q.type===2?'SCAN OK':q.type===3?'TAG FERTIG':'ROUTE OK';el('passStatus').textContent='ETIKETT FERTIG';el('sortJunction').classList.add(q.grammar);el('passengerStage').classList.add('ready','tagged');el('passengerState').textContent='ist richtig vorbereitet';showFeedback(true,q,perfect);el('stampZone').hidden=false;el('stampButton').querySelector('b').textContent=run.phase==='border'&&run.borderIndex===2?'LETZTEN KOFFER VERLADEN':'BAND STARTEN';el('stampButton').onclick=function(){applyStamp(q)};el('stampButton').focus();sound('correct');updateGlobal()}
function showFeedback(ok,q,perfect){var f=document.createElement('div');f.className='feedback show '+(ok?'good':'bad');if(ok){f.innerHTML='<div class="feedback-title">✓ '+(q.type===1?'Route eingestellt!':q.type===2?'Etikett gescannt!':'Koffer-Tag fertig!')+'</div><div class="reward-line"><span>'+asset('star','reward-asset')+' +'+CONFIG.correctPoints+' Sortierpunkte</span><span>+ '+CONFIG.correctTravel+' Reisepunkte</span><span>XP +'+CONFIG.correctXP+'</span>'+(perfect?'<span class="perfect-stamp">'+asset('seal','reward-asset')+' PERFEKT SORTIERT</span>':'')+'</div><b>'+q.sentence+'</b><div>'+q.country.explain+'</div><div class="feedback-actions"><button class="btn secondary" id="speakAnswer">'+asset('sound','inline-asset')+'Vorlesen</button><button class="btn primary" id="next">Nächster Koffer →</button></div>'}else{f.innerHTML='<div class="feedback-title">Fast!</div><p>Der Koffer kommt über die Korrekturspur zurück. Prüfe die Herkunft noch einmal – ohne Minuspunkte.</p>'}el('caseArea').appendChild(f);if(ok){el('speakAnswer').onclick=function(){speak(q.sentence)};el('next').onclick=next}else setTimeout(function(){run.locked=false;document.querySelectorAll('.choice').forEach(function(b){b.classList.remove('wrong')});el('center').classList.remove('wrong-route');el('sortJunction').classList.remove('reverse');el('passengerStage').classList.remove('thinking','returning')},650);el('live').textContent=ok?'Richtig. Koffer vorbereitet. '+q.sentence:'Fast. Der Koffer kommt zurück. Bitte noch einmal versuchen.'}
function applyStamp(q){if(run.stamped)return;run.stamped=true;if(q.mystery)run.special++;el('documentStamp').hidden=false;el('documentStamp').textContent='VERLADEN ✓';el('documentStamp').classList.add('stamp-in');el('passStatus').textContent='VERLADEN ✓';el('stampZone').hidden=true;el('center').classList.add('stamped');el('controlLight').className='control-light good';el('controlLight').querySelector('b').textContent='VERLADEN';el('controlGate').classList.add('open');el('passengerStage').classList.add('approved','loading','route-'+q.grammar);el('passengerState').textContent='fährt zum Flugzeug';if(run.suitcaseReady){run.suitcaseReady=false;run.helpReady=true;toast('Bonus-Koffer geöffnet · Detektiv-Hilfe bereit')}el('next').focus();el('live').textContent='Koffer sortiert und verladen. Nächster Koffer.'}
function checkSeal(g){var thresholds={aus:3,ausDer:2,ausDen:1};if(wg.grammarMastery[g]>=thresholds[g]&&wg.seals.indexOf(g)<0){wg.seals.push(g);addXP(CONFIG.sealXP);toast('Neues Herkunfts-Siegel! '+({aus:'AUS',ausDer:'AUS DER',ausDen:'AUS DEN'}[g])+' gemeistert');if(wg.seals.length===3)awardAchievement('woher-seals','Siegelmeister')}}
function next(){if(!run.stamped)return;el('passengerStage').classList.add('leaving');setTimeout(function(){if(run.phase==='normal'&&run.combo>=CONFIG.bonusChoiceThreshold&&run.bonusChoices<CONFIG.maxBonusChoicesPerRun&&run.index<run.questions.length-1){showCaseChoice();return}advanceCase()},380)}
function advanceCase(){if(run.phase==='normal'){if(run.index<run.questions.length-1){run.index++;render()}else startBorder()}else if(run.borderIndex<2){run.borderIndex++;render()}else completeBorder()}
function showCaseChoice(){run.bonusChoices++;showModal('<span class="station-ribbon">SORTIER-SERIE · WELCHES BAND?</span><h2>Wähle die nächste Förderstrecke</h2><div class="gate-choice"><button class="btn secondary" id="safeCase">← SICHERES BAND</button><button class="btn primary" id="riskCase">EXPRESS-BAND →</button></div><p>Auf dem Express-Band bringt die gleiche nächste Aufgabe '+CONFIG.riskChoicePoints+' Extra-Punkte, wenn du sie perfekt löst.</p>',null);var safe=document.getElementById('safeCase'),risk=document.getElementById('riskCase');safe.onclick=function(){safe.closest('.overlay').remove();advanceCase();el('live').textContent='Sicheres Band gewählt.'};risk.onclick=function(){run.riskBonus=true;risk.closest('.overlay').remove();advanceCase();el('live').textContent='Express-Band aktiviert. Die nächste perfekte Sortierung bringt Bonuspunkte.'};safe.focus()}
function startBorder(){run.phase='border';var pick=function(t){var q=run.questions.find(function(x){return x.type===t});return makeQ(q.type,q.country.name,q.subject,q.person)};run.border=[pick(1),pick(2),pick(3)];run.borderIndex=0;showModal(asset('suitcase','start-plane','Koffer auf dem Förderband')+'<span class="station-ribbon">LETZTER FLUG</span><h1>GEPÄCK-RUSH</h1><p><b>NOCH 3 KOFFER</b><br>Sortiere, scanne und baue einen letzten Koffer-Tag.</p><button class="btn primary" id="modalGo">Gepäck-Rush starten</button>',function(){document.body.classList.add('final-boarding');render()})}
function completeBorder(){wg.borderControlCompleted=true;if(run.borderPerfect){wg.perfectBorderControl=true;addXP(CONFIG.perfectBorderXP);awardAchievement('woher-border-perfect','Perfekter Gepäck-Rush')}addXP(CONFIG.borderXP);el('boardStatus').textContent='GEPÄCK KOMPLETT';el('routeTitle').textContent='LETZTER FLUG · ALLES VERLADEN';el('airportPlane').classList.add('departing');showModal('<div class="departure-payoff"><div class="mini-plane">'+asset('plane','')+'</div></div><h1>FLUG BEREIT!</h1><p>'+(run.borderPerfect?'Perfekter Gepäck-Rush! Alle drei Koffer waren sofort richtig.':'Das ganze Gepäck ist im Flugzeug.')+'</p><button class="btn primary" id="modalGo">Ergebnis ansehen</button>',function(){document.body.classList.remove('final-boarding');finish()})}
function finish(){API.completeGame(progress,'woher',run.score);wg.completed=true;wg.bestScore=Math.max(wg.bestScore||0,run.score);wg.bestCombo=Math.max(wg.bestCombo||0,run.maxCombo);if(!wg.completionRewardClaimed){wg.completionRewardClaimed=true;API.addPoints(progress,CONFIG.completionTravel);addXP(CONFIG.completionXP)}awardAchievement('woher-complete','Herkunftsprofi');var all=completedCount()===4,celebrated=progress.meta&&progress.meta.goldenPassportCelebrated===true;if(all&&!celebrated){progress.meta=progress.meta||{};progress.meta.goldenPassportUnlocked=true;progress.meta.goldenPassportCelebrated=true;awardAchievement('journey-complete','Deutschreise geschafft');save();goldenFinal()}else{save();normalFinal()}}
function normalFinal(){var remaining=['countryMap','dialoge','saetze','woher'].filter(function(k){return !progress.lesson1.games[k].completed}).map(function(k){return {countryMap:'Länder',dialoge:'Dialoge',saetze:'Sätze',woher:'Woher?'}[k]}),sealsLeft=Math.max(0,3-wg.seals.length),medal=run.perfect>=10?'SORTIERMEISTER':run.perfect>=6?'GEPÄCK-PROFI':'REISEBEREIT';showModal(asset('suitcase','start-plane','Gepäck ist verladen')+'<h1>ALLES VERLADEN!</h1><p><b>'+medal+' · Woher? abgeschlossen · '+completedCount()+' / 4 Stationen</b></p><div class="summary-grid"><div>Koffer sortiert<br><b>'+run.correct+'</b></div><div>Richtige Aufgaben<br><b>'+run.correct+'</b></div><div>Sortierpunkte<br><b>'+run.score+'</b></div><div>Beste Sortier-Serie<br><b>x'+run.maxCombo+'</b></div><div>Perfekt sortiert<br><b>'+run.perfect+'</b></div><div>Sondergepäck gefunden<br><b>'+run.special+'</b></div><div>Herkunfts-Siegel<br><b>'+wg.seals.length+' / 3</b></div><div>Bestwert<br><b>'+wg.bestScore+'</b></div></div>'+(sealsLeft?'<p>Noch '+sealsLeft+' Herkunfts-Siegel – in der nächsten Runde kannst du sie sammeln.</p>':'<p>Alle Herkunfts-Siegel gesammelt!</p>')+(remaining.length?'<p>Noch offen: '+remaining.join(', ')+'</p>':'')+'<button class="btn primary" id="replay">Noch eine Runde</button> <a class="btn secondary" href="../index.html">Zur Deutschreise</a>',null)}
function goldenFinal(){window.ReisenAudio?.playFinale();showModal('<img class="gold-pass" src="assets/shared/goldener-reisepass.svg" alt="Goldener Reisepass, Lektion 1"><h1>Lektion 1 geschafft!</h1><p><b>DEUTSCHREISE GESCHAFFT · 4 / 4 · 100 %</b></p><div class="summary-grid"><div>Länder<br><b>Station ✓</b></div><div>Begegnungen<br><b>Station ✓</b></div><div>Reise-Tickets<br><b>Station ✓</b></div><div>Herkunfts-Siegel<br><b>'+wg.seals.length+' / 3</b></div></div><button class="btn primary" id="replay">Spiele wiederholen</button> <a class="btn secondary" href="../index.html">Meine Reise ansehen</a>',null)}
function start(){window.ReisenAudio?.playMusic();run.questions=makeQuestions();run.index=run.score=run.combo=run.maxCombo=run.correct=run.errors=run.perfect=run.special=run.bonusChoices=0;run.riskBonus=false;run.suitcaseReady=false;run.helpReady=false;run.stamped=false;run.borderPerfect=true;run.phase='normal';run.locked=false;wg.plays++;render()}
function tutorial(){showModal('<span class="station-ribbon">SO FUNKTIONIERT KOFFER-CHAOS</span><h2>Bring alle Koffer zum Flugzeug</h2><div class="tutorial-steps"><div><b>1 · Schau auf den Koffer.</b>Flagge und Aufgabe zeigen die Herkunft.</div><div><b>2 · Löse die Aufgabe.</b>Sortiere, scanne oder baue einen Koffer-Tag.</div><div><b>3 · Wähle die richtige Route.</b>Deine Antwort stellt das Förderband ein.</div><div><b>4 · Verlade den Koffer.</b>Starte das Band zum Flugzeug.</div></div><button class="btn primary" id="modalGo">Band starten</button>',function(){wg.introSeen=true;wg.baggageTutorialSeen=true;save();start()})}
function intro(){showModal(asset('suitcase','start-plane','Koffer auf dem Förderband')+'<span class="station-ribbon">REISESTATION 04</span><h1>KOFFER-CHAOS</h1><h2>WOHER? · DAS GEPÄCK-SORTIERSPIEL</h2><p>Sortiere die Koffer und bringe sie zum Flugzeug. Ohne Zeitdruck und ohne Minuspunkte.</p><div class="start-control-actions"><button class="btn primary" id="modalGo">Band starten</button><button class="btn secondary" id="howPlay">Wie spielt man?</button></div>',function(){if(wg.baggageTutorialSeen)start();else tutorial()});setTimeout(function(){var how=document.getElementById('howPlay');if(how)how.onclick=function(){how.closest('.overlay').remove();tutorial()}},0)}
function showModal(html,after){var o=document.createElement('div');o.className='overlay';o.innerHTML='<div class="modal" role="dialog" aria-modal="true">'+html+'</div>';document.body.appendChild(o);var go=o.querySelector('#modalGo');if(go){go.onclick=function(){o.remove();if(after)after()};go.focus()}var replay=o.querySelector('#replay');if(replay)replay.onclick=function(){o.remove();start()}}
function toast(t){var d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(function(){d.remove()},3000)}
function speak(t){window.ReisenAudio?.speak(t,{rate:.88})}
var audioCtx;function sound(type){if(!(window.ReisenAudio?.isSoundEnabled()??run.sound)||(window.ReisenAudio&&!ReisenAudio.sfxAllowed(type==='complete'?'major':'normal')))return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();var notes=type==='wrong'?[210,165]:type==='complete'?[392,523,659,784]:[523,659,784],now=audioCtx.currentTime,volume=(window.ReisenAudio?.getSettings().soundVolume||.7)*.09;notes.forEach(function(n,i){var o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=n;g.gain.setValueAtTime(.001,now+i*.08);g.gain.exponentialRampToValueAtTime(volume,now+i*.08+.01);g.gain.exponentialRampToValueAtTime(.001,now+i*.08+.13);o.connect(g).connect(audioCtx.destination);o.start(now+i*.08);o.stop(now+i*.08+.15)})}catch(e){}}
function updateSoundAsset(){el('sound').innerHTML=asset(run.sound?'sound':'mute','button-asset')}updateSoundAsset();el('sound').onclick=function(){run.sound=!run.sound;localStorage.setItem('woher-game-sound-enabled',String(run.sound));updateSoundAsset()};
document.addEventListener('keydown',function(e){if(run.locked)return;var q=currentQ();if(q&&q.type===1){var routeKey={ArrowLeft:'aus',a:'aus',A:'aus',ArrowDown:'aus der',s:'aus der',S:'aus der',ArrowRight:'aus den',d:'aus den',D:'aus den'}[e.key];if(routeKey){var routeButton=Array.prototype.find.call(document.querySelectorAll('.choice'),function(b){return b.dataset.value===routeKey});if(routeButton){e.preventDefault();routeButton.click();return}}}if(['1','2','3','4'].indexOf(e.key)>=0){var b=document.querySelectorAll('.choice')[Number(e.key)-1];if(b)b.click()}});
function stopPageScroll(e){if(e.target.closest('.modal,.reisen-audio-popover'))return;e.preventDefault()}
window.scrollTo(0,0);window.addEventListener('scroll',function(){window.scrollTo(0,0)},{passive:true});document.addEventListener('wheel',stopPageScroll,{passive:false});document.addEventListener('touchmove',stopPageScroll,{passive:false});updateGlobal();intro();
})();
